# Generated by Django 5.2.7 on 2025-10-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='special_request',
        ),
    ]
